-- migrate:up
INSERT INTO stickers (name, section, card_code, card_type) VALUES
  ('Panini', 'Intro', '00', 'Special'),
  ('Official Emblem 1', 'Intro', 'FWC1', 'Special'),
  ('Official Emblem 2', 'Intro', 'FWC2', 'Special'),
  ('Official Mascots', 'Intro', 'FWC3', 'Special'),
  ('Official Slogan', 'Intro', 'FWC4', 'Special'),
  ('Official Ball', 'Intro', 'FWC5', 'Special'),
  ('Host Country Emblem - Canada', 'Intro', 'FWC6', 'Special'),
  ('Host Country Emblem - Mexico', 'Intro', 'FWC7', 'Special'),
  ('Host Country Emblem - USA', 'Intro', 'FWC8', 'Special'),

  ('Italy 1934', 'World Cup History', 'FWC9', 'Special'),
  ('Uruguay 1950', 'World Cup History', 'FWC10', 'Special'),
  ('West Germany 1954', 'World Cup History', 'FWC11', 'Special'),
  ('Brazil 1962', 'World Cup History', 'FWC12', 'Special'),
  ('West Germany 1974', 'World Cup History', 'FWC13', 'Special'),
  ('Argentina 1986', 'World Cup History', 'FWC14', 'Special'),
  ('Brazil 1994', 'World Cup History', 'FWC15', 'Special'),
  ('Brazil 2002', 'World Cup History', 'FWC16', 'Special'),
  ('Italy 2006', 'World Cup History', 'FWC17', 'Special'),
  ('Germany 2014', 'World Cup History', 'FWC18', 'Special'),
  ('Argentina 2022', 'World Cup History', 'FWC19', 'Special'),

  ('Lamine Yamal', 'Coke / Coca Cola', 'CC1', 'Special'),
  ('Joshua Kimmich', 'Coke / Coca Cola', 'CC2', 'Special'),
  ('Harry Kane', 'Coke / Coca Cola', 'CC3', 'Special'),
  ('Santiago Giménez', 'Coke / Coca Cola', 'CC4', 'Special'),
  ('Josko Gvardiol', 'Coke / Coca Cola', 'CC5', 'Special'),
  ('Federico Valverde', 'Coke / Coca Cola', 'CC6', 'Special'),
  ('Jefferson Lerma', 'Coke / Coca Cola', 'CC7', 'Special'),
  ('Enner Valencia', 'Coke / Coca Cola', 'CC8', 'Special'),
  ('Gabriel Magalhães', 'Coke / Coca Cola', 'CC9', 'Special'),
  ('Virgil van Dijk', 'Coke / Coca Cola', 'CC10', 'Special'),
  ('Alphonso Davies', 'Coke / Coca Cola', 'CC11', 'Special'),
  ('Emiliano Martinez', 'Coke / Coca Cola', 'CC12', 'Special'),
  ('Raúl Jiménez', 'Coke / Coca Cola', 'CC13', 'Special'),
  ('Lautaro Martinez', 'Coke / Coca Cola', 'CC14', 'Special'),

  ('Team Crest', 'Algeria', 'ALG1', 'Crest (Foil)'),
  ('Alexis Guendouz', 'Algeria', 'ALG2', 'Player'),
  ('Ramy Bensebaini', 'Algeria', 'ALG3', 'Player'),
  ('Youcef Atal', 'Algeria', 'ALG4', 'Player'),
  ('Rayan Aït-Nouri', 'Algeria', 'ALG5', 'Player'),
  ('Mohamed Amine Tougai', 'Algeria', 'ALG6', 'Player'),
  ('Aïssa Mandi', 'Algeria', 'ALG7', 'Player'),
  ('Ismael Bennacer', 'Algeria', 'ALG8', 'Player'),
  ('Houssem Aquar', 'Algeria', 'ALG9', 'Player'),
  ('Hicham Boudaoui', 'Algeria', 'ALG10', 'Player'),
  ('Ramiz Zerrouki', 'Algeria', 'ALG11', 'Player'),
  ('Nabil Bentalab', 'Algeria', 'ALG12', 'Player'),
  ('Team Photo', 'Algeria', 'ALG13', 'Team Photo'),
  ('Farés Chaibi', 'Algeria', 'ALG14', 'Player'),
  ('Riyad Mahrez', 'Algeria', 'ALG15', 'Player'),
  ('Said Benrahma', 'Algeria', 'ALG16', 'Player'),
  ('Anis Hadj Moussa', 'Algeria', 'ALG17', 'Player'),
  ('Amine Gouiri', 'Algeria', 'ALG18', 'Player'),
  ('Baghdad Bounedjah', 'Algeria', 'ALG19', 'Player'),
  ('Mohammed Amoura', 'Algeria', 'ALG20', 'Player'),

  ('Team Crest', 'Argentina', 'ARG1', 'Crest (Foil)'),
  ('Emiliano Martinez', 'Argentina', 'ARG2', 'Player'),
  ('Nahuel Molina', 'Argentina', 'ARG3', 'Player'),
  ('Cristian Romero', 'Argentina', 'ARG4', 'Player'),
  ('Nicolas Otamendi', 'Argentina', 'ARG5', 'Player'),
  ('Nicolas Tagliafico', 'Argentina', 'ARG6', 'Player'),
  ('Leonardo Balerdi', 'Argentina', 'ARG7', 'Player'),
  ('Enzo Fernandez', 'Argentina', 'ARG8', 'Player'),
  ('Alexis Mac Allister', 'Argentina', 'ARG9', 'Player'),
  ('Rodrigo De Paul', 'Argentina', 'ARG10', 'Player'),
  ('Exequiel Palacios', 'Argentina', 'ARG11', 'Player'),
  ('Leandro Paredes', 'Argentina', 'ARG12', 'Player'),
  ('Team Photo', 'Argentina', 'ARG13', 'Team Photo'),
  ('Nico Paz', 'Argentina', 'ARG14', 'Player'),
  ('Franco Mastantuono', 'Argentina', 'ARG15', 'Player'),
  ('Nico Gonzalez', 'Argentina', 'ARG16', 'Player'),
  ('Lionel Messi', 'Argentina', 'ARG17', 'Player'),
  ('Lautaro Martinez', 'Argentina', 'ARG18', 'Player'),
  ('Julian Alvarez', 'Argentina', 'ARG19', 'Player'),
  ('Giuliano Simeone', 'Argentina', 'ARG20', 'Player'),

  ('Team Crest', 'Australia', 'AUS1', 'Crest (Foil)'),
  ('Mathew Ryan', 'Australia', 'AUS2', 'Player'),
  ('Joe Gauci', 'Australia', 'AUS3', 'Player'),
  ('Harry Souttar', 'Australia', 'AUS4', 'Player'),
  ('Alessandro Circati', 'Australia', 'AUS5', 'Player'),
  ('Jordan Bos', 'Australia', 'AUS6', 'Player'),
  ('Aziz Behich', 'Australia', 'AUS7', 'Player'),
  ('Cameron Burgess', 'Australia', 'AUS8', 'Player'),
  ('Lewis Miller', 'Australia', 'AUS9', 'Player'),
  ('Milos Degenek', 'Australia', 'AUS10', 'Player'),
  ('Jackson Irvine', 'Australia', 'AUS11', 'Player'),
  ('Riley McGree', 'Australia', 'AUS12', 'Player'),
  ('Team Photo', 'Australia', 'AUS13', 'Team Photo'),
  ('Aiden O''Neill', 'Australia', 'AUS14', 'Player'),
  ('Connor Metcalfe', 'Australia', 'AUS15', 'Player'),
  ('Patrick Yazbek', 'Australia', 'AUS16', 'Player'),
  ('Craig Goodwin', 'Australia', 'AUS17', 'Player'),
  ('Kusini Vengi', 'Australia', 'AUS18', 'Player'),
  ('Nestory Irankunda', 'Australia', 'AUS19', 'Player'),
  ('Mohamed Touré', 'Australia', 'AUS20', 'Player'),

  ('Team Crest', 'Austria', 'AUT1', 'Crest (Foil)'),
  ('Alexander Schlager', 'Austria', 'AUT2', 'Player'),
  ('Patrick Pentz', 'Austria', 'AUT3', 'Player'),
  ('David Alaba', 'Austria', 'AUT4', 'Player'),
  ('Kevin Danso', 'Austria', 'AUT5', 'Player'),
  ('Philipp Lienhart', 'Austria', 'AUT6', 'Player'),
  ('Stefan Posch', 'Austria', 'AUT7', 'Player'),
  ('Phillipp Mwene', 'Austria', 'AUT8', 'Player'),
  ('Alexander Prass', 'Austria', 'AUT9', 'Player'),
  ('Xaver Schlager', 'Austria', 'AUT10', 'Player'),
  ('Marcel Sabitzer', 'Austria', 'AUT11', 'Player'),
  ('Konrad Laimer', 'Austria', 'AUT12', 'Player'),
  ('Team Photo', 'Austria', 'AUT13', 'Team Photo'),
  ('Florian Grillitsch', 'Austria', 'AUT14', 'Player'),
  ('Nicolas Seiwald', 'Austria', 'AUT15', 'Player'),
  ('Romano Schmid', 'Austria', 'AUT16', 'Player'),
  ('Patrick Wimmer', 'Austria', 'AUT17', 'Player'),
  ('Christoph Baumgartner', 'Austria', 'AUT18', 'Player'),
  ('Michael Gregoritsch', 'Austria', 'AUT19', 'Player'),
  ('Marko Arnautović', 'Austria', 'AUT20', 'Player'),

  ('Team Crest', 'Belgium', 'BEL1', 'Crest (Foil)'),
  ('Thibaut Courtois', 'Belgium', 'BEL2', 'Player'),
  ('Arthur Theate', 'Belgium', 'BEL3', 'Player'),
  ('Timothy Castagne', 'Belgium', 'BEL4', 'Player'),
  ('Zeno Debast', 'Belgium', 'BEL5', 'Player'),
  ('Brandon Mechele', 'Belgium', 'BEL6', 'Player'),
  ('Maxim De Cuyper', 'Belgium', 'BEL7', 'Player'),
  ('Thomas Meunier', 'Belgium', 'BEL8', 'Player'),
  ('Youri Tielemans', 'Belgium', 'BEL9', 'Player'),
  ('Amadou Onana', 'Belgium', 'BEL10', 'Player'),
  ('Nicolas Raskin', 'Belgium', 'BEL11', 'Player'),
  ('Alexis Saelemaekers', 'Belgium', 'BEL12', 'Player'),
  ('Team Photo', 'Belgium', 'BEL13', 'Team Photo'),
  ('Hans Vanaken', 'Belgium', 'BEL14', 'Player'),
  ('Kevin De Bruyne', 'Belgium', 'BEL15', 'Player'),
  ('Jérémy Doku', 'Belgium', 'BEL16', 'Player'),
  ('Charles De Ketelaere', 'Belgium', 'BEL17', 'Player'),
  ('Leandro Trossard', 'Belgium', 'BEL18', 'Player'),
  ('Loïs Openda', 'Belgium', 'BEL19', 'Player'),
  ('Romelu Lukaku', 'Belgium', 'BEL20', 'Player'),

  ('Team Crest', 'Bosnia and Herzegovina', 'BIH1', 'Crest (Foil)'),
  ('Nikola Vasilj', 'Bosnia and Herzegovina', 'BIH2', 'Player'),
  ('Amer Dedic', 'Bosnia and Herzegovina', 'BIH3', 'Player'),
  ('Sead Kolasinac', 'Bosnia and Herzegovina', 'BIH4', 'Player'),
  ('Tarik Muharemovic', 'Bosnia and Herzegovina', 'BIH5', 'Player'),
  ('Nihad Mujakic', 'Bosnia and Herzegovina', 'BIH6', 'Player'),
  ('Nikola Katic', 'Bosnia and Herzegovina', 'BIH7', 'Player'),
  ('Amir Hadziahmetovic', 'Bosnia and Herzegovina', 'BIH8', 'Player'),
  ('Benjamin Tahirovic', 'Bosnia and Herzegovina', 'BIH9', 'Player'),
  ('Armin Gigovic', 'Bosnia and Herzegovina', 'BIH10', 'Player'),
  ('Ivan Sunjic', 'Bosnia and Herzegovina', 'BIH11', 'Player'),
  ('Ivan Basic', 'Bosnia and Herzegovina', 'BIH12', 'Player'),
  ('Team Photo', 'Bosnia and Herzegovina', 'BIH13', 'Team Photo'),
  ('Dzenis Burnic', 'Bosnia and Herzegovina', 'BIH14', 'Player'),
  ('Esmir Bajraktarevic', 'Bosnia and Herzegovina', 'BIH15', 'Player'),
  ('Amar Memic', 'Bosnia and Herzegovina', 'BIH16', 'Player'),
  ('Ermedin Demirovic', 'Bosnia and Herzegovina', 'BIH17', 'Player'),
  ('Edin Dzeko', 'Bosnia and Herzegovina', 'BIH18', 'Player'),
  ('Samed Bazdar', 'Bosnia and Herzegovina', 'BIH19', 'Player'),
  ('Haris Tabakovic', 'Bosnia and Herzegovina', 'BIH20', 'Player'),

  ('Team Crest', 'Brazil', 'BRA1', 'Crest (Foil)'),
  ('Alisson', 'Brazil', 'BRA2', 'Player'),
  ('Bento', 'Brazil', 'BRA3', 'Player'),
  ('Marquinhos', 'Brazil', 'BRA4', 'Player'),
  ('Éder Militão', 'Brazil', 'BRA5', 'Player'),
  ('Gabriel Magalhães', 'Brazil', 'BRA6', 'Player'),
  ('Danilo', 'Brazil', 'BRA7', 'Player'),
  ('Wesley', 'Brazil', 'BRA8', 'Player'),
  ('Lucas Paquetá', 'Brazil', 'BRA9', 'Player'),
  ('Casemiro', 'Brazil', 'BRA10', 'Player'),
  ('Bruno Guimarães', 'Brazil', 'BRA11', 'Player'),
  ('Luiz Henrique', 'Brazil', 'BRA12', 'Player'),
  ('Team Photo', 'Brazil', 'BRA13', 'Team Photo'),
  ('Vinicius Júnior', 'Brazil', 'BRA14', 'Player'),
  ('Rodrygo', 'Brazil', 'BRA15', 'Player'),
  ('João Pedro', 'Brazil', 'BRA16', 'Player'),
  ('Matheus Cunha', 'Brazil', 'BRA17', 'Player'),
  ('Gabriel Martinelli', 'Brazil', 'BRA18', 'Player'),
  ('Raphinha', 'Brazil', 'BRA19', 'Player'),
  ('Estévão', 'Brazil', 'BRA20', 'Player'),

  ('Team Crest', 'Canada', 'CAN1', 'Crest (Foil)'),
  ('Dayne St.Clair', 'Canada', 'CAN2', 'Player'),
  ('Alphonso Davies', 'Canada', 'CAN3', 'Player'),
  ('Alistair Johnston', 'Canada', 'CAN4', 'Player'),
  ('Samuel Adekugbe', 'Canada', 'CAN5', 'Player'),
  ('Riche Larvea', 'Canada', 'CAN6', 'Player'),
  ('Derek Cornelius', 'Canada', 'CAN7', 'Player'),
  ('Moïse Bombito', 'Canada', 'CAN8', 'Player'),
  ('Kamal Miller', 'Canada', 'CAN9', 'Player'),
  ('Stephen Eustáquio', 'Canada', 'CAN10', 'Player'),
  ('Ismaël Koné', 'Canada', 'CAN11', 'Player'),
  ('Jonathan Osorio', 'Canada', 'CAN12', 'Player'),
  ('Team Photo', 'Canada', 'CAN13', 'Team Photo'),
  ('Jacob Shaffelburg', 'Canada', 'CAN14', 'Player'),
  ('Mathieu Choinière', 'Canada', 'CAN15', 'Player'),
  ('Niko Sigur', 'Canada', 'CAN16', 'Player'),
  ('Tajon Buchanan', 'Canada', 'CAN17', 'Player'),
  ('Liam Millar', 'Canada', 'CAN18', 'Player'),
  ('Cyle Larin', 'Canada', 'CAN19', 'Player'),
  ('Jonathan David', 'Canada', 'CAN20', 'Player'),

  ('Team Crest', 'Côte d''Ivoire', 'CIV1', 'Crest (Foil)'),
  ('Yahia Fofana', 'Côte d''Ivoire', 'CIV2', 'Player'),
  ('Ghislain Konan', 'Côte d''Ivoire', 'CIV3', 'Player'),
  ('Wilfried Singo', 'Côte d''Ivoire', 'CIV4', 'Player'),
  ('Odilon Kossounou', 'Côte d''Ivoire', 'CIV5', 'Player'),
  ('Evan Ndicka', 'Côte d''Ivoire', 'CIV6', 'Player'),
  ('Willy Boly', 'Côte d''Ivoire', 'CIV7', 'Player'),
  ('Emmanuel Agbadou', 'Côte d''Ivoire', 'CIV8', 'Player'),
  ('Ousmane Diomande', 'Côte d''Ivoire', 'CIV9', 'Player'),
  ('Franck Kessie', 'Côte d''Ivoire', 'CIV10', 'Player'),
  ('Seko Fofana', 'Côte d''Ivoire', 'CIV11', 'Player'),
  ('Ibrahim Sangare', 'Côte d''Ivoire', 'CIV12', 'Player'),
  ('Team Photo', 'Côte d''Ivoire', 'CIV13', 'Team Photo'),
  ('Jean-Philippe Gbamin', 'Côte d''Ivoire', 'CIV14', 'Player'),
  ('Amad Diallo', 'Côte d''Ivoire', 'CIV15', 'Player'),
  ('Sébastien Haller', 'Côte d''Ivoire', 'CIV16', 'Player'),
  ('Simon Adingra', 'Côte d''Ivoire', 'CIV17', 'Player'),
  ('Yan Diomande', 'Côte d''Ivoire', 'CIV18', 'Player'),
  ('Evann Guessand', 'Côte d''Ivoire', 'CIV19', 'Player'),
  ('Oumar Diakite', 'Côte d''Ivoire', 'CIV20', 'Player'),

  ('Team Crest', 'DR Congo', 'COD1', 'Crest (Foil)'),
  ('Lionel Mpasi', 'DR Congo', 'COD2', 'Player'),
  ('Aaron Wan-Bissaka', 'DR Congo', 'COD3', 'Player'),
  ('Axel Tuanzebe', 'DR Congo', 'COD4', 'Player'),
  ('Arthur Masuaku', 'DR Congo', 'COD5', 'Player'),
  ('Chancel Mbemba', 'DR Congo', 'COD6', 'Player'),
  ('Joris Kayembe', 'DR Congo', 'COD7', 'Player'),
  ('Charles Pickel', 'DR Congo', 'COD8', 'Player'),
  ('Ngal''ayel Mukau', 'DR Congo', 'COD9', 'Player'),
  ('Edo Kayembe', 'DR Congo', 'COD10', 'Player'),
  ('Samuel Moutoussamy', 'DR Congo', 'COD11', 'Player'),
  ('Noah Sadiki', 'DR Congo', 'COD12', 'Player'),
  ('Team Photo', 'DR Congo', 'COD13', 'Team Photo'),
  ('Théo Bongonda', 'DR Congo', 'COD14', 'Player'),
  ('Meschak Elia', 'DR Congo', 'COD15', 'Player'),
  ('Yoane Wissa', 'DR Congo', 'COD16', 'Player'),
  ('Brian Cipenga', 'DR Congo', 'COD17', 'Player'),
  ('Fiston Mayele', 'DR Congo', 'COD18', 'Player'),
  ('Cédric Bakambu', 'DR Congo', 'COD19', 'Player'),
  ('Nathanaël Mbuku', 'DR Congo', 'COD20', 'Player'),

  ('Team Crest', 'Colombia', 'COL1', 'Crest (Foil)'),
  ('Camilo Vargas', 'Colombia', 'COL2', 'Player'),
  ('David Ospina', 'Colombia', 'COL3', 'Player'),
  ('Dávinson Sánchez', 'Colombia', 'COL4', 'Player'),
  ('Yerry Mina', 'Colombia', 'COL5', 'Player'),
  ('Daniel Munoz', 'Colombia', 'COL6', 'Player'),
  ('Johan Mojica', 'Colombia', 'COL7', 'Player'),
  ('Jhon Lucumí', 'Colombia', 'COL8', 'Player'),
  ('Santiago Arias', 'Colombia', 'COL9', 'Player'),
  ('Jefferson Lerma', 'Colombia', 'COL10', 'Player'),
  ('Kevin Castaño', 'Colombia', 'COL11', 'Player'),
  ('Richard Rios', 'Colombia', 'COL12', 'Player'),
  ('Team Photo', 'Colombia', 'COL13', 'Team Photo'),
  ('James Rodriguez', 'Colombia', 'COL14', 'Player'),
  ('Juan Fernando Quintero', 'Colombia', 'COL15', 'Player'),
  ('Jorge Carrascal', 'Colombia', 'COL16', 'Player'),
  ('Jon Arias', 'Colombia', 'COL17', 'Player'),
  ('Jhon Cordova', 'Colombia', 'COL18', 'Player'),
  ('Luis Suarez', 'Colombia', 'COL19', 'Player'),
  ('Luis Diaz', 'Colombia', 'COL20', 'Player'),

  ('Team Crest', 'Cape Verde', 'CPV1', 'Crest (Foil)'),
  ('Vozinha', 'Cape Verde', 'CPV2', 'Player'),
  ('Logan Costa', 'Cape Verde', 'CPV3', 'Player'),
  ('Pico', 'Cape Verde', 'CPV4', 'Player'),
  ('Diney', 'Cape Verde', 'CPV5', 'Player'),
  ('Steven Moreira', 'Cape Verde', 'CPV6', 'Player'),
  ('Wagner Pina', 'Cape Verde', 'CPV7', 'Player'),
  ('Joao Paulo', 'Cape Verde', 'CPV8', 'Player'),
  ('Yannick Semedo', 'Cape Verde', 'CPV9', 'Player'),
  ('Kevin Pina', 'Cape Verde', 'CPV10', 'Player'),
  ('Patrick Andrade', 'Cape Verde', 'CPV11', 'Player'),
  ('Jamiro Monteiro', 'Cape Verde', 'CPV12', 'Player'),
  ('Team Photo', 'Cape Verde', 'CPV13', 'Team Photo'),
  ('Deroy Duarte', 'Cape Verde', 'CPV14', 'Player'),
  ('Garry Rodrigues', 'Cape Verde', 'CPV15', 'Player'),
  ('Jovane Cabral', 'Cape Verde', 'CPV16', 'Player'),
  ('Ryan Mendes', 'Cape Verde', 'CPV17', 'Player'),
  ('Dailon Livramento', 'Cape Verde', 'CPV18', 'Player'),
  ('Willy Semedo', 'Cape Verde', 'CPV19', 'Player'),
  ('Bebe', 'Cape Verde', 'CPV20', 'Player'),

  ('Team Crest', 'Croatia', 'CRO1', 'Crest (Foil)'),
  ('Dominik Livaković', 'Croatia', 'CRO2', 'Player'),
  ('Duje Caleta-Car', 'Croatia', 'CRO3', 'Player'),
  ('Josko Gvardiol', 'Croatia', 'CRO4', 'Player'),
  ('Josip Stanišić', 'Croatia', 'CRO5', 'Player'),
  ('Luka Vušković', 'Croatia', 'CRO6', 'Player'),
  ('Josip Sutalo', 'Croatia', 'CRO7', 'Player'),
  ('Kristijan Jakic', 'Croatia', 'CRO8', 'Player'),
  ('Luka Modrić', 'Croatia', 'CRO9', 'Player'),
  ('Mateo Kovacic', 'Croatia', 'CRO10', 'Player'),
  ('Martin Baturina', 'Croatia', 'CRO11', 'Player'),
  ('Lovro Majer', 'Croatia', 'CRO12', 'Player'),
  ('Team Photo', 'Croatia', 'CRO13', 'Team Photo'),
  ('Mario Pasalic', 'Croatia', 'CRO14', 'Player'),
  ('Petar Sucic', 'Croatia', 'CRO15', 'Player'),
  ('Ivan Perišić', 'Croatia', 'CRO16', 'Player'),
  ('Marco Pasalic', 'Croatia', 'CRO17', 'Player'),
  ('Ante Budimir', 'Croatia', 'CRO18', 'Player'),
  ('Andrej Kramarić', 'Croatia', 'CRO19', 'Player'),
  ('Franjo Ivanovic', 'Croatia', 'CRO20', 'Player'),

  ('Team Crest', 'Curaçao', 'CUW1', 'Crest (Foil)'),
  ('Eloy Room', 'Curaçao', 'CUW2', 'Player'),
  ('Armando Obispo', 'Curaçao', 'CUW3', 'Player'),
  ('Sherel Floranus', 'Curaçao', 'CUW4', 'Player'),
  ('Jurien Gaari', 'Curaçao', 'CUW5', 'Player'),
  ('Joshua Brenet', 'Curaçao', 'CUW6', 'Player'),
  ('Roshon Van Eijma', 'Curaçao', 'CUW7', 'Player'),
  ('Shurandy Sambo', 'Curaçao', 'CUW8', 'Player'),
  ('Livano Comenencia', 'Curaçao', 'CUW9', 'Player'),
  ('Godfried Roemeratoe', 'Curaçao', 'CUW10', 'Player'),
  ('Juninho Bacuna', 'Curaçao', 'CUW11', 'Player'),
  ('Leandro Bacuna', 'Curaçao', 'CUW12', 'Player'),
  ('Team Photo', 'Curaçao', 'CUW13', 'Team Photo'),
  ('Tahith Chong', 'Curaçao', 'CUW14', 'Player'),
  ('Kenji Gorre', 'Curaçao', 'CUW15', 'Player'),
  ('Jearl Margaritha', 'Curaçao', 'CUW16', 'Player'),
  ('Jurgen Locadia', 'Curaçao', 'CUW17', 'Player'),
  ('Jeremy Antonisse', 'Curaçao', 'CUW18', 'Player'),
  ('Gervane Kastaneer', 'Curaçao', 'CUW19', 'Player'),
  ('Sontje Hansen', 'Curaçao', 'CUW20', 'Player'),

  ('Team Crest', 'Czechia', 'CZE1', 'Crest (Foil)'),
  ('Matej Kovar', 'Czechia', 'CZE2', 'Player'),
  ('Jindrich Stanek', 'Czechia', 'CZE3', 'Player'),
  ('Ladislav Krejci', 'Czechia', 'CZE4', 'Player'),
  ('Vladimir Coufal', 'Czechia', 'CZE5', 'Player'),
  ('Jaroslav Zeleny', 'Czechia', 'CZE6', 'Player'),
  ('Tomas Holes', 'Czechia', 'CZE7', 'Player'),
  ('David Zima', 'Czechia', 'CZE8', 'Player'),
  ('Michal Sadilek', 'Czechia', 'CZE9', 'Player'),
  ('Lukas Provod', 'Czechia', 'CZE10', 'Player'),
  ('Lukas Cerv', 'Czechia', 'CZE11', 'Player'),
  ('Tomas Soucek', 'Czechia', 'CZE12', 'Player'),
  ('Team Photo', 'Czechia', 'CZE13', 'Team Photo'),
  ('Pavel Sulc', 'Czechia', 'CZE14', 'Player'),
  ('Matej Vydra', 'Czechia', 'CZE15', 'Player'),
  ('Vasil Kusej', 'Czechia', 'CZE16', 'Player'),
  ('Tomas Chory', 'Czechia', 'CZE17', 'Player'),
  ('Vaclav Cerny', 'Czechia', 'CZE18', 'Player'),
  ('Adam Hlozek', 'Czechia', 'CZE19', 'Player'),
  ('Patrik Schick', 'Czechia', 'CZE20', 'Player'),

  ('Team Crest', 'Ecuador', 'ECU1', 'Crest (Foil)'),
  ('Hernán Galíndez', 'Ecuador', 'ECU2', 'Player'),
  ('Gonzalo Valle', 'Ecuador', 'ECU3', 'Player'),
  ('Piero Hincapié', 'Ecuador', 'ECU4', 'Player'),
  ('Pervis Estupiñán', 'Ecuador', 'ECU5', 'Player'),
  ('Willian Pacho', 'Ecuador', 'ECU6', 'Player'),
  ('Ángelo Preciado', 'Ecuador', 'ECU7', 'Player'),
  ('Joel Ordóñez', 'Ecuador', 'ECU8', 'Player'),
  ('Moises Caicedo', 'Ecuador', 'ECU9', 'Player'),
  ('Alan Franco', 'Ecuador', 'ECU10', 'Player'),
  ('Kendry Paez', 'Ecuador', 'ECU11', 'Player'),
  ('Pedro Vite', 'Ecuador', 'ECU12', 'Player'),
  ('Team Photo', 'Ecuador', 'ECU13', 'Team Photo'),
  ('John Veboah', 'Ecuador', 'ECU14', 'Player'),
  ('Leonardo Campana', 'Ecuador', 'ECU15', 'Player'),
  ('Gonzalo Plata', 'Ecuador', 'ECU16', 'Player'),
  ('Nilson Angulo', 'Ecuador', 'ECU17', 'Player'),
  ('Alan Minda', 'Ecuador', 'ECU18', 'Player'),
  ('Kevin Rodriguez', 'Ecuador', 'ECU19', 'Player'),
  ('Enner Valencia', 'Ecuador', 'ECU20', 'Player'),

  ('Team Crest', 'Egypt', 'EGY1', 'Crest (Foil)'),
  ('Mohamed El Shenawy', 'Egypt', 'EGY2', 'Player'),
  ('Mohamed Hany', 'Egypt', 'EGY3', 'Player'),
  ('Mohamed Hamdy', 'Egypt', 'EGY4', 'Player'),
  ('Yasser Ibrahim', 'Egypt', 'EGY5', 'Player'),
  ('Khaled Sobhi', 'Egypt', 'EGY6', 'Player'),
  ('Ramy Rabia', 'Egypt', 'EGY7', 'Player'),
  ('Hossam Abdelmaguid', 'Egypt', 'EGY8', 'Player'),
  ('Ahmed Fatouh', 'Egypt', 'EGY9', 'Player'),
  ('Marwan Attia', 'Egypt', 'EGY10', 'Player'),
  ('Zizo', 'Egypt', 'EGY11', 'Player'),
  ('Hamdy Fathy', 'Egypt', 'EGY12', 'Player'),
  ('Team Photo', 'Egypt', 'EGY13', 'Team Photo'),
  ('Mohamed Lasheen', 'Egypt', 'EGY14', 'Player'),
  ('Emam Ashour', 'Egypt', 'EGY15', 'Player'),
  ('Osama Faisal', 'Egypt', 'EGY16', 'Player'),
  ('Mohamed Salah', 'Egypt', 'EGY17', 'Player'),
  ('Mostafa Mohamed', 'Egypt', 'EGY18', 'Player'),
  ('Trezeguet', 'Egypt', 'EGY19', 'Player'),
  ('Omar Marmoush', 'Egypt', 'EGY20', 'Player'),

  ('Team Crest', 'England', 'ENG1', 'Crest (Foil)'),
  ('Jordan Pickford', 'England', 'ENG2', 'Player'),
  ('John Stones', 'England', 'ENG3', 'Player'),
  ('Marc Guéhi', 'England', 'ENG4', 'Player'),
  ('Ezri Konsa', 'England', 'ENG5', 'Player'),
  ('Trent Alexander-Arnold', 'England', 'ENG6', 'Player'),
  ('Reece James', 'England', 'ENG7', 'Player'),
  ('Dan Burn', 'England', 'ENG8', 'Player'),
  ('Jordan Henderson', 'England', 'ENG9', 'Player'),
  ('Declan Rice', 'England', 'ENG10', 'Player'),
  ('Jude Bellingham', 'England', 'ENG11', 'Player'),
  ('Cole Palmer', 'England', 'ENG12', 'Player'),
  ('Team Photo', 'England', 'ENG13', 'Team Photo'),
  ('Morgan Rogers', 'England', 'ENG14', 'Player'),
  ('Anthony Gordon', 'England', 'ENG15', 'Player'),
  ('Phil Foden', 'England', 'ENG16', 'Player'),
  ('Bukayo Saka', 'England', 'ENG17', 'Player'),
  ('Harry Kane', 'England', 'ENG18', 'Player'),
  ('Marcus Rashford', 'England', 'ENG19', 'Player'),
  ('Ollie Watkins', 'England', 'ENG20', 'Player'),

  ('Team Crest', 'Spain', 'ESP1', 'Crest (Foil)'),
  ('Unai Simon', 'Spain', 'ESP2', 'Player'),
  ('Robin Le Normand', 'Spain', 'ESP3', 'Player'),
  ('Aymeric Laporte', 'Spain', 'ESP4', 'Player'),
  ('Dean Huijsen', 'Spain', 'ESP5', 'Player'),
  ('Pedro Porro', 'Spain', 'ESP6', 'Player'),
  ('Dani Carvajal', 'Spain', 'ESP7', 'Player'),
  ('Marc Cucurella', 'Spain', 'ESP8', 'Player'),
  ('Martín Zubimendi', 'Spain', 'ESP9', 'Player'),
  ('Rodri', 'Spain', 'ESP10', 'Player'),
  ('Pedri', 'Spain', 'ESP11', 'Player'),
  ('Fabian Ruiz', 'Spain', 'ESP12', 'Player'),
  ('Team Photo', 'Spain', 'ESP13', 'Team Photo'),
  ('Mikel Merino', 'Spain', 'ESP14', 'Player'),
  ('Lamine Yamal', 'Spain', 'ESP15', 'Player'),
  ('Dani Olmo', 'Spain', 'ESP16', 'Player'),
  ('Nico Williams', 'Spain', 'ESP17', 'Player'),
  ('Ferran Torres', 'Spain', 'ESP18', 'Player'),
  ('Álvaro Morata', 'Spain', 'ESP19', 'Player'),
  ('Mikel Oyarzabal', 'Spain', 'ESP20', 'Player'),

  ('Team Crest', 'France', 'FRA1', 'Crest (Foil)'),
  ('Mike Maignan', 'France', 'FRA2', 'Player'),
  ('Theo Hernandez', 'France', 'FRA3', 'Player'),
  ('William Saliba', 'France', 'FRA4', 'Player'),
  ('Jules Kounde', 'France', 'FRA5', 'Player'),
  ('Ibrahima Konate', 'France', 'FRA6', 'Player'),
  ('Dayot Upamecano', 'France', 'FRA7', 'Player'),
  ('Lucas Digne', 'France', 'FRA8', 'Player'),
  ('Aurélien Tchouaméni', 'France', 'FRA9', 'Player'),
  ('Eduardo Camavinga', 'France', 'FRA10', 'Player'),
  ('Manu Kone', 'France', 'FRA11', 'Player'),
  ('Adrien Rabiot', 'France', 'FRA12', 'Player'),
  ('Team Photo', 'France', 'FRA13', 'Team Photo'),
  ('Michael Olise', 'France', 'FRA14', 'Player'),
  ('Ousmane Dembele', 'France', 'FRA15', 'Player'),
  ('Bradley Barcola', 'France', 'FRA16', 'Player'),
  ('Désiré Doué', 'France', 'FRA17', 'Player'),
  ('Kingsley Coman', 'France', 'FRA18', 'Player'),
  ('Hugo Ekitike', 'France', 'FRA19', 'Player'),
  ('Kylian Mbappe', 'France', 'FRA20', 'Player'),

  ('Team Crest', 'Germany', 'GER1', 'Crest (Foil)'),
  ('Marc-André ter Stegen', 'Germany', 'GER2', 'Player'),
  ('Jonathan Tah', 'Germany', 'GER3', 'Player'),
  ('David Raum', 'Germany', 'GER4', 'Player'),
  ('Nico Schlotterbeck', 'Germany', 'GER5', 'Player'),
  ('Antonio Rüdiger', 'Germany', 'GER6', 'Player'),
  ('Waldemar Anton', 'Germany', 'GER7', 'Player'),
  ('Ridle Baku', 'Germany', 'GER8', 'Player'),
  ('Maximilian Mittelstadt', 'Germany', 'GER9', 'Player'),
  ('Joshua Kimmich', 'Germany', 'GER10', 'Player'),
  ('Florian Wirtz', 'Germany', 'GER11', 'Player'),
  ('Felix Nmecha', 'Germany', 'GER12', 'Player'),
  ('Team Photo', 'Germany', 'GER13', 'Team Photo'),
  ('Leon Goretzka', 'Germany', 'GER14', 'Player'),
  ('Jamal Musiala', 'Germany', 'GER15', 'Player'),
  ('Serge Gnabry', 'Germany', 'GER16', 'Player'),
  ('Kai Havertz', 'Germany', 'GER17', 'Player'),
  ('Leroy Sane', 'Germany', 'GER18', 'Player'),
  ('Karim Adeyemi', 'Germany', 'GER19', 'Player'),
  ('Nick Woltemade', 'Germany', 'GER20', 'Player'),

  ('Team Crest', 'Ghana', 'GHA1', 'Crest (Foil)'),
  ('Lawrence Ati Zigi', 'Ghana', 'GHA2', 'Player'),
  ('Tariq Lamptey', 'Ghana', 'GHA3', 'Player'),
  ('Mohammed Salisu', 'Ghana', 'GHA4', 'Player'),
  ('Alidu Seidu', 'Ghana', 'GHA5', 'Player'),
  ('Alexander Djiku', 'Ghana', 'GHA6', 'Player'),
  ('Gideon Mensah', 'Ghana', 'GHA7', 'Player'),
  ('Caleb Yirenkyi', 'Ghana', 'GHA8', 'Player'),
  ('Abdul Issahaku Fatawu', 'Ghana', 'GHA9', 'Player'),
  ('Thomas Partey', 'Ghana', 'GHA10', 'Player'),
  ('Salis Abdul Samed', 'Ghana', 'GHA11', 'Player'),
  ('Kamaldeen Sulemana', 'Ghana', 'GHA12', 'Player'),
  ('Team Photo', 'Ghana', 'GHA13', 'Team Photo'),
  ('Mohammed Kudus', 'Ghana', 'GHA14', 'Player'),
  ('Inaki Williams', 'Ghana', 'GHA15', 'Player'),
  ('Jordan Ayew', 'Ghana', 'GHA16', 'Player'),
  ('Andrew Ayew', 'Ghana', 'GHA17', 'Player'),
  ('Joseph Paintsil', 'Ghana', 'GHA18', 'Player'),
  ('Osman Bukari', 'Ghana', 'GHA19', 'Player'),
  ('Antoine Semenyo', 'Ghana', 'GHA20', 'Player'),

  ('Team Crest', 'Haiti', 'HAI1', 'Crest (Foil)'),
  ('Johny Placide', 'Haiti', 'HAI2', 'Player'),
  ('Carlens Arcus', 'Haiti', 'HAI3', 'Player'),
  ('Martin Expérience', 'Haiti', 'HAI4', 'Player'),
  ('Jean-Kevin Duverne', 'Haiti', 'HAI5', 'Player'),
  ('Ricardo Adé', 'Haiti', 'HAI6', 'Player'),
  ('Duke Lacroix', 'Haiti', 'HAI7', 'Player'),
  ('Garven Metusala', 'Haiti', 'HAI8', 'Player'),
  ('Hannes Delcroix', 'Haiti', 'HAI9', 'Player'),
  ('Leverton Pierre', 'Haiti', 'HAI10', 'Player'),
  ('Danley Jean Jacques', 'Haiti', 'HAI11', 'Player'),
  ('Jean-Ricner Bellegarde', 'Haiti', 'HAI12', 'Player'),
  ('Team Photo', 'Haiti', 'HAI13', 'Team Photo'),
  ('Christopher Attys', 'Haiti', 'HAI14', 'Player'),
  ('Derrick Etienne Jr', 'Haiti', 'HAI15', 'Player'),
  ('Josue Casimir', 'Haiti', 'HAI16', 'Player'),
  ('Ruben Providence', 'Haiti', 'HAI17', 'Player'),
  ('Duckens Nazon', 'Haiti', 'HAI18', 'Player'),
  ('Louicius Deedson', 'Haiti', 'HAI19', 'Player'),
  ('Frantzdy Pierrot', 'Haiti', 'HAI20', 'Player'),

  ('Team Crest', 'Iran', 'IRN1', 'Crest (Foil)'),
  ('Alireza Beiranvand', 'Iran', 'IRN2', 'Player'),
  ('Morteza Pouraliganji', 'Iran', 'IRN3', 'Player'),
  ('Ehsan Hajsafi', 'Iran', 'IRN4', 'Player'),
  ('Milad Mohammadi', 'Iran', 'IRN5', 'Player'),
  ('Shojae Khalilzadeh', 'Iran', 'IRN6', 'Player'),
  ('Ramin Rezaeian', 'Iran', 'IRN7', 'Player'),
  ('Hossein Kanaani', 'Iran', 'IRN8', 'Player'),
  ('Sadegh Moharrami', 'Iran', 'IRN9', 'Player'),
  ('Saleh Hardani', 'Iran', 'IRN10', 'Player'),
  ('Saeed Ezatolahi', 'Iran', 'IRN11', 'Player'),
  ('Saman Ghoddos', 'Iran', 'IRN12', 'Player'),
  ('Team Photo', 'Iran', 'IRN13', 'Team Photo'),
  ('Omid Noorafkan', 'Iran', 'IRN14', 'Player'),
  ('Roozbeh Cheshmi', 'Iran', 'IRN15', 'Player'),
  ('Mohammad Mohebi', 'Iran', 'IRN16', 'Player'),
  ('Sardar Azmoun', 'Iran', 'IRN17', 'Player'),
  ('Mehdi Taremi', 'Iran', 'IRN18', 'Player'),
  ('Alireza Jahanbakhsh', 'Iran', 'IRN19', 'Player'),
  ('Ali Gholizadeh', 'Iran', 'IRN20', 'Player'),

  ('Team Crest', 'Iraq', 'IRQ1', 'Crest (Foil)'),
  ('Jalal Hassan', 'Iraq', 'IRQ2', 'Player'),
  ('Rebin Sulaka', 'Iraq', 'IRQ3', 'Player'),
  ('Hussein Ali', 'Iraq', 'IRQ4', 'Player'),
  ('Akam Hashem', 'Iraq', 'IRQ5', 'Player'),
  ('Merchas Doski', 'Iraq', 'IRQ6', 'Player'),
  ('Zaid Tahseen', 'Iraq', 'IRQ7', 'Player'),
  ('Manaf Younis', 'Iraq', 'IRQ8', 'Player'),
  ('Zidane Iqbal', 'Iraq', 'IRQ9', 'Player'),
  ('Amir Al-Ammari', 'Iraq', 'IRQ10', 'Player'),
  ('Ibrahim Bavesh', 'Iraq', 'IRQ11', 'Player'),
  ('Ali Jasim', 'Iraq', 'IRQ12', 'Player'),
  ('Team Photo', 'Iraq', 'IRQ13', 'Team Photo'),
  ('Youssef Amyn', 'Iraq', 'IRQ14', 'Player'),
  ('Aimar Sher', 'Iraq', 'IRQ15', 'Player'),
  ('Marko Farji', 'Iraq', 'IRQ16', 'Player'),
  ('Osama Rashid', 'Iraq', 'IRQ17', 'Player'),
  ('Ali Al-Hamadi', 'Iraq', 'IRQ18', 'Player'),
  ('Aymen Hussein', 'Iraq', 'IRQ19', 'Player'),
  ('Mohanad Ali', 'Iraq', 'IRQ20', 'Player'),

  ('Team Crest', 'Jordan', 'JOR1', 'Crest (Foil)'),
  ('Yazeed Abulaila', 'Jordan', 'JOR2', 'Player'),
  ('Ihsan Haddad', 'Jordan', 'JOR3', 'Player'),
  ('Mohammad Abu Hashish', 'Jordan', 'JOR4', 'Player'),
  ('Yazan Al-Arab', 'Jordan', 'JOR5', 'Player'),
  ('Abdallah Nasib', 'Jordan', 'JOR6', 'Player'),
  ('Saleem Obaid', 'Jordan', 'JOR7', 'Player'),
  ('Mohammad Abualnadi', 'Jordan', 'JOR8', 'Player'),
  ('Ibrahim Saadeh', 'Jordan', 'JOR9', 'Player'),
  ('Nizar Al-Rashdan', 'Jordan', 'JOR10', 'Player'),
  ('Noor Al-Rawabdeh', 'Jordan', 'JOR11', 'Player'),
  ('Mohannad Abu Taha', 'Jordan', 'JOR12', 'Player'),
  ('Team Photo', 'Jordan', 'JOR13', 'Team Photo'),
  ('Amer Jamous', 'Jordan', 'JOR14', 'Player'),
  ('Musa Al-Taamari', 'Jordan', 'JOR15', 'Player'),
  ('Yazan Al-Naimat', 'Jordan', 'JOR16', 'Player'),
  ('Mahmoud Al-Mardi', 'Jordan', 'JOR17', 'Player'),
  ('Ali Olwan', 'Jordan', 'JOR18', 'Player'),
  ('Mohammad Abu Zrayq', 'Jordan', 'JOR19', 'Player'),
  ('Ibrahim Sabra', 'Jordan', 'JOR20', 'Player'),

  ('Team Crest', 'Japan', 'JPN1', 'Crest (Foil)'),
  ('Zion Suzuki', 'Japan', 'JPN2', 'Player'),
  ('Henry Heroki Mochizuki', 'Japan', 'JPN3', 'Player'),
  ('Ayumu Seko', 'Japan', 'JPN4', 'Player'),
  ('Junnosuke Suzuki', 'Japan', 'JPN5', 'Player'),
  ('Shogo Taniguchi', 'Japan', 'JPN6', 'Player'),
  ('Tsuyoshi Watanabe', 'Japan', 'JPN7', 'Player'),
  ('Kaishu Sano', 'Japan', 'JPN8', 'Player'),
  ('Yuki Soma', 'Japan', 'JPN9', 'Player'),
  ('Ao Tanaka', 'Japan', 'JPN10', 'Player'),
  ('Daichi Kamada', 'Japan', 'JPN11', 'Player'),
  ('Takefusa Kubo', 'Japan', 'JPN12', 'Player'),
  ('Team Photo', 'Japan', 'JPN13', 'Team Photo'),
  ('Ritsu Doan', 'Japan', 'JPN14', 'Player'),
  ('Keito Nakamura', 'Japan', 'JPN15', 'Player'),
  ('Takumi Minamino', 'Japan', 'JPN16', 'Player'),
  ('Shuto Machino', 'Japan', 'JPN17', 'Player'),
  ('Junya Ito', 'Japan', 'JPN18', 'Player'),
  ('Koki Ogawa', 'Japan', 'JPN19', 'Player'),
  ('Ayase Ueda', 'Japan', 'JPN20', 'Player'),

  ('Team Crest', 'South Korea', 'KOR1', 'Crest (Foil)'),
  ('Hyeon-woo Jo', 'South Korea', 'KOR2', 'Player'),
  ('Seung-Gyu Kim', 'South Korea', 'KOR3', 'Player'),
  ('Min-jae Kim', 'South Korea', 'KOR4', 'Player'),
  ('Yu-min Cho', 'South Korea', 'KOR5', 'Player'),
  ('Young-woo Seol', 'South Korea', 'KOR6', 'Player'),
  ('Han-beom Lee', 'South Korea', 'KOR7', 'Player'),
  ('Tae-seok Lee', 'South Korea', 'KOR8', 'Player'),
  ('Myung-jae Lee', 'South Korea', 'KOR9', 'Player'),
  ('Jae-sung Lee', 'South Korea', 'KOR10', 'Player'),
  ('In-beom Hwang', 'South Korea', 'KOR11', 'Player'),
  ('Kang-in Lee', 'South Korea', 'KOR12', 'Player'),
  ('Team Photo', 'South Korea', 'KOR13', 'Team Photo'),
  ('Seung-ho Paik', 'South Korea', 'KOR14', 'Player'),
  ('Jens Castrop', 'South Korea', 'KOR15', 'Player'),
  ('Dongg-yeong Lee', 'South Korea', 'KOR16', 'Player'),
  ('Gue-sung Cho', 'South Korea', 'KOR17', 'Player'),
  ('Heung-min Son', 'South Korea', 'KOR18', 'Player'),
  ('Hee-chan Hwang', 'South Korea', 'KOR19', 'Player'),
  ('Hyeon-Gyu Oh', 'South Korea', 'KOR20', 'Player'),

  ('Team Crest', 'Saudi Arabia', 'KSA1', 'Crest (Foil)'),
  ('Nawaf Alaqidi', 'Saudi Arabia', 'KSA2', 'Player'),
  ('Abdulrahman Al-Sanbi', 'Saudi Arabia', 'KSA3', 'Player'),
  ('Saud Abdulhamid', 'Saudi Arabia', 'KSA4', 'Player'),
  ('Nawaf Bouwashl', 'Saudi Arabia', 'KSA5', 'Player'),
  ('Jihad Thakri', 'Saudi Arabia', 'KSA6', 'Player'),
  ('Moteb Al-Harbi', 'Saudi Arabia', 'KSA7', 'Player'),
  ('Hassan Altambakti', 'Saudi Arabia', 'KSA8', 'Player'),
  ('Musab Aljuwayr', 'Saudi Arabia', 'KSA9', 'Player'),
  ('Ziyad Aljohani', 'Saudi Arabia', 'KSA10', 'Player'),
  ('Abdullah Alkhaibari', 'Saudi Arabia', 'KSA11', 'Player'),
  ('Nasser Aldawsari', 'Saudi Arabia', 'KSA12', 'Player'),
  ('Team Photo', 'Saudi Arabia', 'KSA13', 'Team Photo'),
  ('Saleh Abu Alshamat', 'Saudi Arabia', 'KSA14', 'Player'),
  ('Marwan Alsahafi', 'Saudi Arabia', 'KSA15', 'Player'),
  ('Salem Aldawsari', 'Saudi Arabia', 'KSA16', 'Player'),
  ('Abdulrahman Al-Aboud', 'Saudi Arabia', 'KSA17', 'Player'),
  ('Feras Akbrikan', 'Saudi Arabia', 'KSA18', 'Player'),
  ('Saleh Alshehri', 'Saudi Arabia', 'KSA19', 'Player'),
  ('Abdullah Al-Hamdan', 'Saudi Arabia', 'KSA20', 'Player'),

  ('Team Crest', 'Morocco', 'MAR1', 'Crest (Foil)'),
  ('Yassine Bounou', 'Morocco', 'MAR2', 'Player'),
  ('Munir El Kajoui', 'Morocco', 'MAR3', 'Player'),
  ('Achraf Hakimi', 'Morocco', 'MAR4', 'Player'),
  ('Noussair Mazraoui', 'Morocco', 'MAR5', 'Player'),
  ('Nayef Aguerd', 'Morocco', 'MAR6', 'Player'),
  ('Roman Saiss', 'Morocco', 'MAR7', 'Player'),
  ('Jawad El Yamio', 'Morocco', 'MAR8', 'Player'),
  ('Adam Masina', 'Morocco', 'MAR9', 'Player'),
  ('Sofyan Amrabat', 'Morocco', 'MAR10', 'Player'),
  ('Azzedine Ounahi', 'Morocco', 'MAR11', 'Player'),
  ('Eliesse Ben Seghir', 'Morocco', 'MAR12', 'Player'),
  ('Team Photo', 'Morocco', 'MAR13', 'Team Photo'),
  ('Bilal El Khannouss', 'Morocco', 'MAR14', 'Player'),
  ('Ismael Saibari', 'Morocco', 'MAR15', 'Player'),
  ('Youssef En-Nesyri', 'Morocco', 'MAR16', 'Player'),
  ('Abde Ezzalzouli', 'Morocco', 'MAR17', 'Player'),
  ('Soufiane Rahimi', 'Morocco', 'MAR18', 'Player'),
  ('Brahim Diaz', 'Morocco', 'MAR19', 'Player'),
  ('Ayoub El Kaabi', 'Morocco', 'MAR20', 'Player'),

  ('Team Crest', 'Mexico', 'MEX1', 'Crest (Foil)'),
  ('Luis Malagón', 'Mexico', 'MEX2', 'Player'),
  ('Johan Vasquez', 'Mexico', 'MEX3', 'Player'),
  ('Jorge Sánchez', 'Mexico', 'MEX4', 'Player'),
  ('Cesar Montes', 'Mexico', 'MEX5', 'Player'),
  ('Jesus Gallardo', 'Mexico', 'MEX6', 'Player'),
  ('Israel Reyes', 'Mexico', 'MEX7', 'Player'),
  ('Diego Lainez', 'Mexico', 'MEX8', 'Player'),
  ('Carlos Rodriguez', 'Mexico', 'MEX9', 'Player'),
  ('Edson Alvarez', 'Mexico', 'MEX10', 'Player'),
  ('Orbelin Pineda', 'Mexico', 'MEX11', 'Player'),
  ('Marcel Ruiz', 'Mexico', 'MEX12', 'Player'),
  ('Team Photo', 'Mexico', 'MEX13', 'Team Photo'),
  ('Érick Sánchez', 'Mexico', 'MEX14', 'Player'),
  ('Hirving Lozano', 'Mexico', 'MEX15', 'Player'),
  ('Santiago Giménez', 'Mexico', 'MEX16', 'Player'),
  ('Raúl Jiménez', 'Mexico', 'MEX17', 'Player'),
  ('Alexis Vega', 'Mexico', 'MEX18', 'Player'),
  ('Roberto Alvarado', 'Mexico', 'MEX19', 'Player'),
  ('Cesar Huerta', 'Mexico', 'MEX20', 'Player'),

  ('Team Crest', 'Netherlands', 'NED1', 'Crest (Foil)'),
  ('Bart Verbruggen', 'Netherlands', 'NED2', 'Player'),
  ('Virgil van Dijk', 'Netherlands', 'NED3', 'Player'),
  ('Micky van de Ven', 'Netherlands', 'NED4', 'Player'),
  ('Jurrien Timber', 'Netherlands', 'NED5', 'Player'),
  ('Denzel Dumfries', 'Netherlands', 'NED6', 'Player'),
  ('Nathan Aké', 'Netherlands', 'NED7', 'Player'),
  ('Jeremie Frimpong', 'Netherlands', 'NED8', 'Player'),
  ('Jan Paul van Hecke', 'Netherlands', 'NED9', 'Player'),
  ('Tijjani Reijnders', 'Netherlands', 'NED10', 'Player'),
  ('Ryan Gravenberch', 'Netherlands', 'NED11', 'Player'),
  ('Teun Koopmeiners', 'Netherlands', 'NED12', 'Player'),
  ('Team Photo', 'Netherlands', 'NED13', 'Team Photo'),
  ('Frenkie de Jong', 'Netherlands', 'NED14', 'Player'),
  ('Xavi Simons', 'Netherlands', 'NED15', 'Player'),
  ('Justin Kluivert', 'Netherlands', 'NED16', 'Player'),
  ('Memphis Depay', 'Netherlands', 'NED17', 'Player'),
  ('Donyell Malen', 'Netherlands', 'NED18', 'Player'),
  ('Wout Weghorst', 'Netherlands', 'NED19', 'Player'),
  ('Cody Gakpo', 'Netherlands', 'NED20', 'Player'),

  ('Team Crest', 'Norway', 'NOR1', 'Crest (Foil)'),
  ('Orjan Nyland', 'Norway', 'NOR2', 'Player'),
  ('Julian Ryerson', 'Norway', 'NOR3', 'Player'),
  ('Leo Ostigård', 'Norway', 'NOR4', 'Player'),
  ('Kristoffer Vassbakk Ajer', 'Norway', 'NOR5', 'Player'),
  ('Marcus Holmgren Pedersen', 'Norway', 'NOR6', 'Player'),
  ('David Møller Wolfe', 'Norway', 'NOR7', 'Player'),
  ('Torbjørn Heggem', 'Norway', 'NOR8', 'Player'),
  ('Morten Thorsby', 'Norway', 'NOR9', 'Player'),
  ('Martin Ødegaard', 'Norway', 'NOR10', 'Player'),
  ('Sander Berge', 'Norway', 'NOR11', 'Player'),
  ('Andreas Schjelderup', 'Norway', 'NOR12', 'Player'),
  ('Team Photo', 'Norway', 'NOR13', 'Team Photo'),
  ('Patrick Berg', 'Norway', 'NOR14', 'Player'),
  ('Erling Haaland', 'Norway', 'NOR15', 'Player'),
  ('Alexander Sørloth', 'Norway', 'NOR16', 'Player'),
  ('Aron Dønnum', 'Norway', 'NOR17', 'Player'),
  ('Jorgen Strand Larsen', 'Norway', 'NOR18', 'Player'),
  ('Antonio Nusa', 'Norway', 'NOR19', 'Player'),
  ('Oscar Bobb', 'Norway', 'NOR20', 'Player'),

  ('Team Crest', 'New Zealand', 'NZL1', 'Crest (Foil)'),
  ('Max Crocombe Payne', 'New Zealand', 'NZL2', 'Player'),
  ('Alex Paulsen', 'New Zealand', 'NZL3', 'Player'),
  ('Michael Boxall', 'New Zealand', 'NZL4', 'Player'),
  ('Liberato Cacace', 'New Zealand', 'NZL5', 'Player'),
  ('Tim Payne', 'New Zealand', 'NZL6', 'Player'),
  ('Tyler Bindon', 'New Zealand', 'NZL7', 'Player'),
  ('Francis de Vries', 'New Zealand', 'NZL8', 'Player'),
  ('Finn Surman', 'New Zealand', 'NZL9', 'Player'),
  ('Joe Bell', 'New Zealand', 'NZL10', 'Player'),
  ('Sarpreet Singh', 'New Zealand', 'NZL11', 'Player'),
  ('Ryan Thomas', 'New Zealand', 'NZL12', 'Player'),
  ('Team Photo', 'New Zealand', 'NZL13', 'Team Photo'),
  ('Matthew Garbett', 'New Zealand', 'NZL14', 'Player'),
  ('Marko Stamenić', 'New Zealand', 'NZL15', 'Player'),
  ('Ben Old', 'New Zealand', 'NZL16', 'Player'),
  ('Chris Wood', 'New Zealand', 'NZL17', 'Player'),
  ('Elijah Just', 'New Zealand', 'NZL18', 'Player'),
  ('Callum McCowatt', 'New Zealand', 'NZL19', 'Player'),
  ('Kosta Barbarouses', 'New Zealand', 'NZL20', 'Player'),

  ('Team Crest', 'Panama', 'PAN1', 'Crest (Foil)'),
  ('Orlando Mosquera', 'Panama', 'PAN2', 'Player'),
  ('Luis Mejia', 'Panama', 'PAN3', 'Player'),
  ('Fidel Escobar', 'Panama', 'PAN4', 'Player'),
  ('Andres Andrade', 'Panama', 'PAN5', 'Player'),
  ('Michael Amir Murillo', 'Panama', 'PAN6', 'Player'),
  ('Eric Davis', 'Panama', 'PAN7', 'Player'),
  ('Jose Cordoba', 'Panama', 'PAN8', 'Player'),
  ('Cesar Blackman', 'Panama', 'PAN9', 'Player'),
  ('Cristian Martinez', 'Panama', 'PAN10', 'Player'),
  ('Aníbal Godoy', 'Panama', 'PAN11', 'Player'),
  ('Adalberto Carrasquilla', 'Panama', 'PAN12', 'Player'),
  ('Team Photo', 'Panama', 'PAN13', 'Team Photo'),
  ('Édgar Bárcenas', 'Panama', 'PAN14', 'Player'),
  ('Carlos Harvey', 'Panama', 'PAN15', 'Player'),
  ('Ismael Díaz', 'Panama', 'PAN16', 'Player'),
  ('Jose Fajardo', 'Panama', 'PAN17', 'Player'),
  ('Cecilio Waterman', 'Panama', 'PAN18', 'Player'),
  ('Jose Luiz Rodriguez', 'Panama', 'PAN19', 'Player'),
  ('Alberto Quintero', 'Panama', 'PAN20', 'Player'),

  ('Team Crest', 'Paraguay', 'PAR1', 'Crest (Foil)'),
  ('Roberto Fernandez', 'Paraguay', 'PAR2', 'Player'),
  ('Orlando Gill', 'Paraguay', 'PAR3', 'Player'),
  ('Gustavo Gomez', 'Paraguay', 'PAR4', 'Player'),
  ('Fabián Balbuena', 'Paraguay', 'PAR5', 'Player'),
  ('Juan José Cáceres', 'Paraguay', 'PAR6', 'Player'),
  ('Omar Alderete', 'Paraguay', 'PAR7', 'Player'),
  ('Junior Alonso', 'Paraguay', 'PAR8', 'Player'),
  ('Mathías Villasanti', 'Paraguay', 'PAR9', 'Player'),
  ('Diego Gomez', 'Paraguay', 'PAR10', 'Player'),
  ('Damián Bobadilla', 'Paraguay', 'PAR11', 'Player'),
  ('Andres Cubas', 'Paraguay', 'PAR12', 'Player'),
  ('Team Photo', 'Paraguay', 'PAR13', 'Team Photo'),
  ('Matias Galarza Fonda', 'Paraguay', 'PAR14', 'Player'),
  ('Julio Enciso', 'Paraguay', 'PAR15', 'Player'),
  ('Alejandro Romero Gamarra', 'Paraguay', 'PAR16', 'Player'),
  ('Miguel Almirón', 'Paraguay', 'PAR17', 'Player'),
  ('Ramon Sosa', 'Paraguay', 'PAR18', 'Player'),
  ('Angel Romero', 'Paraguay', 'PAR19', 'Player'),
  ('Antonio Sanabria', 'Paraguay', 'PAR20', 'Player'),

  ('Team Crest', 'Portugal', 'POR1', 'Crest (Foil)'),
  ('Diogo Costa', 'Portugal', 'POR2', 'Player'),
  ('Jose Sa', 'Portugal', 'POR3', 'Player'),
  ('Ruben Dias', 'Portugal', 'POR4', 'Player'),
  ('João Cancelo', 'Portugal', 'POR5', 'Player'),
  ('Diogo Dalot', 'Portugal', 'POR6', 'Player'),
  ('Nuno Mendes', 'Portugal', 'POR7', 'Player'),
  ('Gonçalo Inácio', 'Portugal', 'POR8', 'Player'),
  ('Bernardo Silva', 'Portugal', 'POR9', 'Player'),
  ('Bruno Fernandes', 'Portugal', 'POR10', 'Player'),
  ('Ruben Neves', 'Portugal', 'POR11', 'Player'),
  ('Vitinha', 'Portugal', 'POR12', 'Player'),
  ('Team Photo', 'Portugal', 'POR13', 'Team Photo'),
  ('João Neves', 'Portugal', 'POR14', 'Player'),
  ('Cristiano Ronaldo', 'Portugal', 'POR15', 'Player'),
  ('Francisco Trincao', 'Portugal', 'POR16', 'Player'),
  ('João Felix', 'Portugal', 'POR17', 'Player'),
  ('Gonçalo Ramos', 'Portugal', 'POR18', 'Player'),
  ('Pedro Neto', 'Portugal', 'POR19', 'Player'),
  ('Rafael Leão', 'Portugal', 'POR20', 'Player'),

  ('Team Crest', 'Qatar', 'QAT1', 'Crest (Foil)'),
  ('Meshaal Barsham', 'Qatar', 'QAT2', 'Player'),
  ('Sultan Albrake', 'Qatar', 'QAT3', 'Player'),
  ('Lucas Mendes', 'Qatar', 'QAT4', 'Player'),
  ('Homam Ahmed', 'Qatar', 'QAT5', 'Player'),
  ('Boualem Khoukhi', 'Qatar', 'QAT6', 'Player'),
  ('Pedro Miguel', 'Qatar', 'QAT7', 'Player'),
  ('Tarek Salman', 'Qatar', 'QAT8', 'Player'),
  ('Mohamed Al-Mannai', 'Qatar', 'QAT9', 'Player'),
  ('Karim Boudiaf', 'Qatar', 'QAT10', 'Player'),
  ('Assim Madibo', 'Qatar', 'QAT11', 'Player'),
  ('Ahmed Fatehi', 'Qatar', 'QAT12', 'Player'),
  ('Team Photo', 'Qatar', 'QAT13', 'Team Photo'),
  ('Mohammed Waad', 'Qatar', 'QAT14', 'Player'),
  ('Abdulaziz Hatem', 'Qatar', 'QAT15', 'Player'),
  ('Hassan Al-Haydos', 'Qatar', 'QAT16', 'Player'),
  ('Edmilson Junior', 'Qatar', 'QAT17', 'Player'),
  ('Akram Hassan Afif', 'Qatar', 'QAT18', 'Player'),
  ('Ahmed Al Ganehi', 'Qatar', 'QAT19', 'Player'),
  ('Almoez Ali', 'Qatar', 'QAT20', 'Player'),

  ('Team Crest', 'South Africa', 'RSA1', 'Crest (Foil)'),
  ('Ronwen Williams', 'South Africa', 'RSA2', 'Player'),
  ('Sipho Chaine', 'South Africa', 'RSA3', 'Player'),
  ('Aubrey Modiba', 'South Africa', 'RSA4', 'Player'),
  ('Samukele Kabini', 'South Africa', 'RSA5', 'Player'),
  ('Mbekezeli Mbokazi', 'South Africa', 'RSA6', 'Player'),
  ('Khulumani Ndamane', 'South Africa', 'RSA7', 'Player'),
  ('Siyabonga Ngezana', 'South Africa', 'RSA8', 'Player'),
  ('Khuliso Mudau', 'South Africa', 'RSA9', 'Player'),
  ('Nkosinathi Sibisi', 'South Africa', 'RSA10', 'Player'),
  ('Teboho Mokoena', 'South Africa', 'RSA11', 'Player'),
  ('Thalente Mbatha', 'South Africa', 'RSA12', 'Player'),
  ('Team Photo', 'South Africa', 'RSA13', 'Team Photo'),
  ('Bathasi Aubaas', 'South Africa', 'RSA14', 'Player'),
  ('Yaya Sithole', 'South Africa', 'RSA15', 'Player'),
  ('Sipho Mbule', 'South Africa', 'RSA16', 'Player'),
  ('Lyle Foster', 'South Africa', 'RSA17', 'Player'),
  ('Iqraam Rayners', 'South Africa', 'RSA18', 'Player'),
  ('Mohau Nkota', 'South Africa', 'RSA19', 'Player'),
  ('Oswin Appollis', 'South Africa', 'RSA20', 'Player'),

  ('Team Crest', 'Scotland', 'SCO1', 'Crest (Foil)'),
  ('Angus Gunn', 'Scotland', 'SCO2', 'Player'),
  ('Jack Hendry', 'Scotland', 'SCO3', 'Player'),
  ('Kieran Tierney', 'Scotland', 'SCO4', 'Player'),
  ('Aaron Hickey', 'Scotland', 'SCO5', 'Player'),
  ('Andrew Robertson', 'Scotland', 'SCO6', 'Player'),
  ('Scott McKenna', 'Scotland', 'SCO7', 'Player'),
  ('John Souttar', 'Scotland', 'SCO8', 'Player'),
  ('Anthony Ralston', 'Scotland', 'SCO9', 'Player'),
  ('Grant Hanley', 'Scotland', 'SCO10', 'Player'),
  ('Scott McTominay', 'Scotland', 'SCO11', 'Player'),
  ('Billy Gilmour', 'Scotland', 'SCO12', 'Player'),
  ('Team Photo', 'Scotland', 'SCO13', 'Team Photo'),
  ('Lewis Ferguson', 'Scotland', 'SCO14', 'Player'),
  ('Ryan Christie', 'Scotland', 'SCO15', 'Player'),
  ('Kenny McLean', 'Scotland', 'SCO16', 'Player'),
  ('John McGinn', 'Scotland', 'SCO17', 'Player'),
  ('Lyndon Dykes', 'Scotland', 'SCO18', 'Player'),
  ('Che Adams', 'Scotland', 'SCO19', 'Player'),
  ('Ben Gannon-Doak', 'Scotland', 'SCO20', 'Player'),

  ('Team Crest', 'Senegal', 'SEN1', 'Crest (Foil)'),
  ('Edouard Mendy', 'Senegal', 'SEN2', 'Player'),
  ('Yehvann Diouf', 'Senegal', 'SEN3', 'Player'),
  ('Moussa Niakhaté', 'Senegal', 'SEN4', 'Player'),
  ('Abdoulaye Seck', 'Senegal', 'SEN5', 'Player'),
  ('Ismail Jakobs', 'Senegal', 'SEN6', 'Player'),
  ('El Hadji Malick Diouf', 'Senegal', 'SEN7', 'Player'),
  ('Kalidou Koulibaly', 'Senegal', 'SEN8', 'Player'),
  ('Idrissa Gana Gueye', 'Senegal', 'SEN9', 'Player'),
  ('Pape Matar Sarr', 'Senegal', 'SEN10', 'Player'),
  ('Pape Gueye', 'Senegal', 'SEN11', 'Player'),
  ('Habib Diarra', 'Senegal', 'SEN12', 'Player'),
  ('Team Photo', 'Senegal', 'SEN13', 'Team Photo'),
  ('Lamine Camara', 'Senegal', 'SEN14', 'Player'),
  ('Sadio Mane', 'Senegal', 'SEN15', 'Player'),
  ('Ismaïla Sarr', 'Senegal', 'SEN16', 'Player'),
  ('Boulaye Dia', 'Senegal', 'SEN17', 'Player'),
  ('Iliman Ndiaye', 'Senegal', 'SEN18', 'Player'),
  ('Nicolas Jackson', 'Senegal', 'SEN19', 'Player'),
  ('Krepin Diatta', 'Senegal', 'SEN20', 'Player'),

  ('Team Crest', 'Switzerland', 'SUI1', 'Crest (Foil)'),
  ('Gregor Kobel', 'Switzerland', 'SUI2', 'Player'),
  ('Yvon Mvogo', 'Switzerland', 'SUI3', 'Player'),
  ('Manuel Akanji', 'Switzerland', 'SUI4', 'Player'),
  ('Ricardo Rodriguez', 'Switzerland', 'SUI5', 'Player'),
  ('Nico Elvedi', 'Switzerland', 'SUI6', 'Player'),
  ('Aurèle Amenda', 'Switzerland', 'SUI7', 'Player'),
  ('Silvan Widmer', 'Switzerland', 'SUI8', 'Player'),
  ('Granit Xhaka', 'Switzerland', 'SUI9', 'Player'),
  ('Denis Zakaria', 'Switzerland', 'SUI10', 'Player'),
  ('Remo Freuler', 'Switzerland', 'SUI11', 'Player'),
  ('Fabian Rieder', 'Switzerland', 'SUI12', 'Player'),
  ('Team Photo', 'Switzerland', 'SUI13', 'Team Photo'),
  ('Ardon Jashari', 'Switzerland', 'SUI14', 'Player'),
  ('Johan Manzambi', 'Switzerland', 'SUI15', 'Player'),
  ('Michel Aebischer', 'Switzerland', 'SUI16', 'Player'),
  ('Breel Embolo', 'Switzerland', 'SUI17', 'Player'),
  ('Ruben Vargas', 'Switzerland', 'SUI18', 'Player'),
  ('Dan Ndoye', 'Switzerland', 'SUI19', 'Player'),
  ('Zeki Amdouni', 'Switzerland', 'SUI20', 'Player'),

  ('Team Crest', 'Sweden', 'SWE1', 'Crest (Foil)'),
  ('Victor Johansson', 'Sweden', 'SWE2', 'Player'),
  ('Isak Hien', 'Sweden', 'SWE3', 'Player'),
  ('Gabriel Gudmundsson', 'Sweden', 'SWE4', 'Player'),
  ('Emil Holm', 'Sweden', 'SWE5', 'Player'),
  ('Victor Nilsson Lindelöf', 'Sweden', 'SWE6', 'Player'),
  ('Gustaf Lagerbielke', 'Sweden', 'SWE7', 'Player'),
  ('Lucas Bergvall', 'Sweden', 'SWE8', 'Player'),
  ('Hugo Larsson', 'Sweden', 'SWE9', 'Player'),
  ('Jesper Karlström', 'Sweden', 'SWE10', 'Player'),
  ('Yasin Ayari', 'Sweden', 'SWE11', 'Player'),
  ('Mattias Svanberg', 'Sweden', 'SWE12', 'Player'),
  ('Team Photo', 'Sweden', 'SWE13', 'Team Photo'),
  ('Daniel Svensson', 'Sweden', 'SWE14', 'Player'),
  ('Ken Sema', 'Sweden', 'SWE15', 'Player'),
  ('Roony Bardghji', 'Sweden', 'SWE16', 'Player'),
  ('Dejan Kulusevski', 'Sweden', 'SWE17', 'Player'),
  ('Anthony Elanga', 'Sweden', 'SWE18', 'Player'),
  ('Alexander Isak', 'Sweden', 'SWE19', 'Player'),
  ('Viktor Gyökeres', 'Sweden', 'SWE20', 'Player'),

  ('Team Crest', 'Tunisia', 'TUN1', 'Crest (Foil)'),
  ('Bechir Ben Said', 'Tunisia', 'TUN2', 'Player'),
  ('Aymen Dahmen', 'Tunisia', 'TUN3', 'Player'),
  ('Yan Valery', 'Tunisia', 'TUN4', 'Player'),
  ('Montassar Talbi', 'Tunisia', 'TUN5', 'Player'),
  ('Yassine Meriah', 'Tunisia', 'TUN6', 'Player'),
  ('Ali Abdi', 'Tunisia', 'TUN7', 'Player'),
  ('Dylan Bronn', 'Tunisia', 'TUN8', 'Player'),
  ('Ellyes Skhiri', 'Tunisia', 'TUN9', 'Player'),
  ('Aissa Laidouni', 'Tunisia', 'TUN10', 'Player'),
  ('Ferjani Sassi', 'Tunisia', 'TUN11', 'Player'),
  ('Mohamed Ali Ben Romdhane', 'Tunisia', 'TUN12', 'Player'),
  ('Team Photo', 'Tunisia', 'TUN13', 'Team Photo'),
  ('Hannibal Mejbri', 'Tunisia', 'TUN14', 'Player'),
  ('Elias Achouri', 'Tunisia', 'TUN15', 'Player'),
  ('Elias Saad', 'Tunisia', 'TUN16', 'Player'),
  ('Hazem Mastouri', 'Tunisia', 'TUN17', 'Player'),
  ('Ismael Gharbi', 'Tunisia', 'TUN18', 'Player'),
  ('Sayfallah Ltaief', 'Tunisia', 'TUN19', 'Player'),
  ('Naim Sliti', 'Tunisia', 'TUN20', 'Player'),

  ('Team Crest', 'Turkey', 'TUR1', 'Crest (Foil)'),
  ('Ugurcan Cakir', 'Turkey', 'TUR2', 'Player'),
  ('Mert Muldur', 'Turkey', 'TUR3', 'Player'),
  ('Zeki Celik', 'Turkey', 'TUR4', 'Player'),
  ('Abdulkerim Bardakci', 'Turkey', 'TUR5', 'Player'),
  ('Caglar Soyuncu', 'Turkey', 'TUR6', 'Player'),
  ('Merih Demiral', 'Turkey', 'TUR7', 'Player'),
  ('Ferdi Kadioglu', 'Turkey', 'TUR8', 'Player'),
  ('Kaan Ayhan', 'Turkey', 'TUR9', 'Player'),
  ('Ismail Yuksek', 'Turkey', 'TUR10', 'Player'),
  ('Hakan Calhanoglu', 'Turkey', 'TUR11', 'Player'),
  ('Orkun Kokcu', 'Turkey', 'TUR12', 'Player'),
  ('Team Photo', 'Turkey', 'TUR13', 'Team Photo'),
  ('Arda Guler', 'Turkey', 'TUR14', 'Player'),
  ('Irfan Can Kahveci', 'Turkey', 'TUR15', 'Player'),
  ('Yunus Akgun', 'Turkey', 'TUR16', 'Player'),
  ('Can Uzun', 'Turkey', 'TUR17', 'Player'),
  ('Baris Alper Yilmaz', 'Turkey', 'TUR18', 'Player'),
  ('Kerem Akturkoglu', 'Turkey', 'TUR19', 'Player'),
  ('Kenan Yildiz', 'Turkey', 'TUR20', 'Player'),

  ('Team Crest', 'Uruguay', 'URU1', 'Crest (Foil)'),
  ('Sergio Rochet', 'Uruguay', 'URU2', 'Player'),
  ('Santiago Mele', 'Uruguay', 'URU3', 'Player'),
  ('Ronald Araujo', 'Uruguay', 'URU4', 'Player'),
  ('José María Giménez', 'Uruguay', 'URU5', 'Player'),
  ('Sebastian Caceres', 'Uruguay', 'URU6', 'Player'),
  ('Mathias Olivera', 'Uruguay', 'URU7', 'Player'),
  ('Guillermo Varela', 'Uruguay', 'URU8', 'Player'),
  ('Nahitan Nandez', 'Uruguay', 'URU9', 'Player'),
  ('Federico Valverde', 'Uruguay', 'URU10', 'Player'),
  ('Giorgian De Arrascaeta', 'Uruguay', 'URU11', 'Player'),
  ('Rodrigo Bentancur', 'Uruguay', 'URU12', 'Player'),
  ('Team Photo', 'Uruguay', 'URU13', 'Team Photo'),
  ('Manuel Ugarte', 'Uruguay', 'URU14', 'Player'),
  ('Nicolás de la Cruz', 'Uruguay', 'URU15', 'Player'),
  ('Maxi Araujo', 'Uruguay', 'URU16', 'Player'),
  ('Darwin Núñez', 'Uruguay', 'URU17', 'Player'),
  ('Federico Viñas', 'Uruguay', 'URU18', 'Player'),
  ('Rodrigo Aguirre', 'Uruguay', 'URU19', 'Player'),
  ('Facundo Pellistri', 'Uruguay', 'URU20', 'Player'),

  ('Team Crest', 'United States', 'USA1', 'Crest (Foil)'),
  ('Math Freese', 'United States', 'USA2', 'Player'),
  ('Chris Richards', 'United States', 'USA3', 'Player'),
  ('Tim Ream', 'United States', 'USA4', 'Player'),
  ('Mark McKenzie', 'United States', 'USA5', 'Player'),
  ('Alex Freeman', 'United States', 'USA6', 'Player'),
  ('Antonee Robinson', 'United States', 'USA7', 'Player'),
  ('Tyler Adams', 'United States', 'USA8', 'Player'),
  ('Tanner Tessmann', 'United States', 'USA9', 'Player'),
  ('Weston McKenny', 'United States', 'USA10', 'Player'),
  ('Christian Roldan', 'United States', 'USA11', 'Player'),
  ('Timothy Weah', 'United States', 'USA12', 'Player'),
  ('Team Photo', 'United States', 'USA13', 'Team Photo'),
  ('Diego Luna', 'United States', 'USA14', 'Player'),
  ('Malik Tillman', 'United States', 'USA15', 'Player'),
  ('Christian Pulisic', 'United States', 'USA16', 'Player'),
  ('Brenden Aaronson', 'United States', 'USA17', 'Player'),
  ('Ricardo Pepi', 'United States', 'USA18', 'Player'),
  ('Haji Wright', 'United States', 'USA19', 'Player'),
  ('Folarin Balogun', 'United States', 'USA20', 'Player'),

  ('Team Crest', 'Uzbekistan', 'UZB1', 'Crest (Foil)'),
  ('Utkir Yusupov', 'Uzbekistan', 'UZB2', 'Player'),
  ('Farrukh Savfiev', 'Uzbekistan', 'UZB3', 'Player'),
  ('Sherzod Nasrullaev', 'Uzbekistan', 'UZB4', 'Player'),
  ('Umar Eshmurodov', 'Uzbekistan', 'UZB5', 'Player'),
  ('Husniddin Aliqulov', 'Uzbekistan', 'UZB6', 'Player'),
  ('Rustamjon Ashurmatov', 'Uzbekistan', 'UZB7', 'Player'),
  ('Khojiakbar Alijonov', 'Uzbekistan', 'UZB8', 'Player'),
  ('Abdukodir Khusanov', 'Uzbekistan', 'UZB9', 'Player'),
  ('Odiljon Hamrobekov', 'Uzbekistan', 'UZB10', 'Player'),
  ('Otabek Shukurov', 'Uzbekistan', 'UZB11', 'Player'),
  ('Jamshid Iskanderov', 'Uzbekistan', 'UZB12', 'Player'),
  ('Team Photo', 'Uzbekistan', 'UZB13', 'Team Photo'),
  ('Azizbek Turgunboev', 'Uzbekistan', 'UZB14', 'Player'),
  ('Khojimat Erkinov', 'Uzbekistan', 'UZB15', 'Player'),
  ('Eldor Shomurodov', 'Uzbekistan', 'UZB16', 'Player'),
  ('Oston Urunov', 'Uzbekistan', 'UZB17', 'Player'),
  ('Jaloliddin Masharipov', 'Uzbekistan', 'UZB18', 'Player'),
  ('Igor Sergeev', 'Uzbekistan', 'UZB19', 'Player'),
  ('Abbosbek Fayzullaev', 'Uzbekistan', 'UZB20', 'Player')

-- migrate:down
TRUNCATE TABLE stickers;

