apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-collector
  namespace: album-collector
  labels:
    app: album-collector
spec:
  # Replicas omitted, as the HPA owns the replica count
  selector:
    # Deployment manages each pod carrying this label
    matchLabels:
      app: album-collector
  template:
    metadata:
      labels:
        app: album-collector
    spec:
      # Pod-level security
      securityContext:
        runAsNonRoot: true # refuses to start if image would run as root
        runAsUser: 1000 # numeric UID of "node" user
        # Filter syscalls the app can make to the container runtime (containerd)
        # curated profile
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          # Replaced with the SHA-tagged ECR image via sed in the pipeline
          image: __IMAGE__
          # Doesn't actually open any ports, simply informational
          ports:
            - containerPort: 3000
          # Pull keys from ConfigMap and Secret as env variables
          envFrom:
            # From configMap
            - configMapRef:
                name: app-config
            # From ESO
            - secretRef:
                name: app-secrets
          resources:
            # What the scheduler reserves/requests - what's read by HPA
            requests:
              cpu: 100m # m = millicores. So 100m = 0.1 CPU cores
              memory: 128Mi
            # Exceed CPU and Pod throttles. Exceed Mem and Pod is OOM-killed
            limits:
              cpu: 500m
              memory: 512Mi
          # Container-level security
          securityContext:
            # No process can gain more privileges than its parent
            allowPrivilegeEscalation: false
            # Drop all default Linux privileges
            # Ex: Change file ownership, system files, raw network packets
            capabilities:
              drop: ["ALL"]
          # liveness/readiness don't begin until this passes
          startupProbe:
            httpGet:
              path: /health/live
              port: 3000
            # 150s to account for Aurora cold starts + app boot
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              # Does not hit DB, just the app
              path: /health/live
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
          # Pod is not restarted on failure,
          # it is held until the DB responds
          readinessProbe:
            httpGet:
              # Hits DB
              path: /health/ready
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
