apiVersion: v1
kind: Service
metadata:
  name: album-collector
  namespace: album-collector
  labels:
    app: album-collector
spec:
  # Service only reachable from inside the cluster
  # It gets an internal IP
  type: ClusterIP
  # Register all pods carrying this label
  selector:
    app: album-collector
  ports:
    # The port the Service listens on
    - port: 80
      # The port on the pods to forward to
      targetPort: 3000
      protocol: TCP
