# ESO continuously syncs this into a native k8s Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  # A pod can only mount a Secret from its own namespace, so we 
  # namespace this
  namespace: album-collector
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  # The output: the native k8s secret ESO will make
  target:
    name: app-secrets
    creationPolicy: Owner # ESO creates and fully owns this Secret
  data:
    # The key in the k8s secret, thus also the env var the app will see
    - secretKey: DB_PASSWORD
      # Which Secrets Manager secret to read
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:822902368026:secret:rds!cluster-bdf75772-1024-4e3d-a3c5-9bbfe803a40e-WDIgQ2
        # Aurora's RDS-managed master password is a JSON, so we need to 
        # extract just the password field
        property: password
    - secretKey: COGNITO_CLIENT_SECRET
      remoteRef:
        key: album-collector/cognito-client-secret
