# ESO continuously syncs this into a native k8s Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: album-collector
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner # ESO creates and fully owns this Secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:822902368026:secret:rds!cluster-bdf75772-1024-4e3d-a3c5-9bbfe803a40e-WDIgQ2
        property: password
    - secretKey: COGNITO_CLIENT_SECRET
      remoteRef:
        key: album-collector/cognito-client-secret
