apiVersion: v1
kind: Namespace
metadata:
  name: album-collector
  labels: 
    # Enforce the Restricted controls defined in the Kubernetes Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest